### ISSUE TITLE
Reference the source

### ISSUE THREAD

**Issue by letienne** [carloscuezva/teslamate-abrp#1]
Hi Carlos,

I'm amused to see that this is your third attempt at re-publishing my code without mentioning me. I'm still unsure why you would want to do something like that with open source code ?

Could you please bring forward the license, copyright and mention the fork?

As @fetzu pointed out yesterday in one of your previous attempt : "You are free not to mention the fork anywhere (it is just bad practice) but you MUST keep the original copyright notice and attribution in the LICENSE file (feel free to add yourself there, but @letienne has to be specifically mentioned)."

(And no, simply renaming variables doesn't count)

Thank you !

**Comment by carloscuezva** [comment]
He puesto el código tal y como TÚ lo mandaste en un pull request y ahora vienes con esto, intente abrir el PR pero al no poder hacerlo lo añadí como pusiste. No sé a que juegas

**Comment by letienne** [comment]
Ok, my bad, sorry. This is now ok for me, even if I would have preferred a fork.

Thank you and kind regards

**Comment by fetzu** [comment]
@letienne in this case, @carloscuezva did copy your LICENSE (and kept your name in it) and added a reference to your repo in the README. IMO he did finally do the right thing (unfortunately, getting GitHub to how the repo as a fork after the fact is not possible, at least that I know of).

**Comment by letienne** [comment]
Yes sorry, I overreacted when I saw the repo. I should have read carefully.

**Comment by carloscuezva** [comment]
No problem.  I apologize for the inconveniences, I have been registered in Github for several years but I had never started using it until now and I am a bit lost.
